## 3.3 Eliminação de Gauss-Jordan e matriz inversa

Os métodos diretos de eliminação consistem no processo 
de transformar um sistema de equações lineares $Ax=b$, em que $A= (a_{ij})_i,j=1,\ldots,n$, 
$x=(x_1,x_2,\ldots,x_n)^t$ e $b=(b_1, b_2,\ldots,b_n)^t$, em um sistema equivalente, 
aplicando operações elementares sobre as linhas da matriz $(A,b)$.

O sistema equivalente obtido ao final do processo, deve ser de 
resolução mais simples ou imediata, por substituição direta. No caso da eliminação de Gauss 
com pivoteamento diagonal ou pivoteamento parcial, obtém-se um sistema equivalente 
na forma triangular. No caso da eliminação de Gauss-Jordan o sistema equivalente 
obtido possui a matriz de coeficientes igual a matriz identidade (forma escalonada reduzida).   

**Exemplo 3.3.1:** ([Fonte](https://integrada.minhabiblioteca.com.br/reader/books/9788522127238/pageid/29)) Use a eliminação de Gauss-Jordan para resolver o sistema

$$
\begin{aligned}
x-2 y+3 z & =9 \\
-x+3 y & =-4 \\
2 x-5 y+5 z & =17
\end{aligned}
$$


A matriz aumentada associada ao sistema é:

$$
\left[\begin{array}{rrrr}
1 & -2 & 3 & 9 \\
-1 & 3 & 0 & -4 \\
2 & -5 & 5 & 17
\end{array}\right]
$$


Substituindo a 2ª linha por ela mesma subtraída da 1ª linha ($L_2 = L_2-L_1$) e a 3ª linha por ela mesma subtraida da 1ª linha multiplicada por $2$ ($L_3 = L_3-2L_1$), obtém-se

$$
\left[\begin{array}{rrrr}
1 & -2 & 3 & 9 \\
0 & 1 & 3 & 5 \\
0 & -1 & -1 & -1
\end{array}\right]
$$

Agora, substituindo a 1ª linha por ela mesma somada da 2ª linha multiplicada por $2$ ($L_1 = L_1+2L_2$) e a 3ª linha por ela mesma somada à 2ª ($L_3=L_3+L_2$), obtém-se

$$
\left[\begin{array}{rrrr}
1 & 0 & 9 & 19 \\
0 & 1 & 3 & 5 \\
0 & 0 & 2 & 4
\end{array}\right]
$$

Por fim, dividindo a 3ª linha por $2$, então, substituindo a 1ª pela 3ª multiplicada por $-9$ ($L_1=L_1-9L3$) e a 2ª por ela mesma multiplicada por $-3$, obtém-se:

$$
\left[\begin{array}{rrrr}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & -1 \\
0 & 0 & 1 & 2
\end{array}\right]
$$

A matriz está agora na forma escalonada reduzida. Convertendo de volta para um sistema de equações lineares, tem-se


$$
\begin{aligned}
& x=1 \\
& y=-1 \\
& z=2 .
\end{aligned}
$$

Usando Python podemos fazer:

In [1]:
import numpy as np

In [2]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

In [3]:
Ab = np.array([[1,-2,3,9],[-1,3,0,-4],[2,-5,5,17]])
Ab

array([[ 1, -2,  3,  9],
       [-1,  3,  0, -4],
       [ 2, -5,  5, 17]])

In [4]:
gaussJordan(Ab)

array([[ 1,  0,  0,  1],
       [ 0,  1,  0, -1],
       [ 0,  0,  1,  2]])

In [5]:
print ('Solução:', Ab[:,-1])

Solução: [ 1 -1  2]


### Método Gauss-Jordan e matriz inversa

Considere o sistema de $n$ equações e $n$ variáveis dado por 

$$Ax=b$$

Se a matriz $A$ dos coeficientes for não singular, ou seja, se o sistema possuir solução única a matriz é invertível e a solução do sistema pode ser obtida multiplicando-se a inversa $A^{-1}$ à esquerda de ambos os lados da equação, como segue: 

$$A^{-1}Ax=A^{-1}b$$

logo

$$Ix = A^{-1}b$$

ou

$$x = A^{-1}b$$

Que é a solução do sistema linear.

Podemos obter a inversa da matriz $A$ por eliminação da Gauss-Jordam aplicando a eliminação à matriz aumentada $[A \mid I ]$ em que $I$ é a matriz identidade de mesma ordem de $A$. Ao final da eliminação obtemos a matriz $[I \mid A^{-1}]$ em que $A^{-1}$ é a inversa da matriz $A$.

**Exemplo 3.3.2:** Resolva o sistema $Ax=b$ usando a matriz inversa de $A$, sendo $A = 
 \left[\begin{array}{ccc} 
	         3 & 0 & 1 \\ 
	         3 & 2 & 1 \\
            -3 & 1 & 3 \\
	     \end{array} \right]$
e $b = (1,1,3)^t$.   

In [6]:
import numpy as np

In [7]:
A = np.array([[3,0,1],[3,2,1],[-3,1,3]])
b = np.array([1,1,3])
x = np.dot(np.linalg.inv(A),b)
print (np.round(x,4))

[-0.  0.  1.]


A obtenção inversa pode ser feita pelo processo de eliminação de Gauss-Jordan em que são realizadas operações elementares sobre as linhas da matriz $A$ até que ela se torne uma matriz identidade. 

Essas mesmas operações são realizadas em uma matriz identidade de mesma ordem, ao final das operações na matriz identidade, o resultado é a inversa da matriz $A$. O exemplo a seguir implementa o processo de eliminação de Gauss-Jordan para obter a inversa de uma matriz $A$.

**Exemplo 3.3.2:** Vamos nesse exemplo utilizar o processo de eliminação de Gauss-Jordan para obter a matriz inversa de 

$$A = 
 \left[\begin{array}{ccc} 
	         2 & 1 & 3 \\ 
	         0 & -1 & 1 \\
            1 & 0 & 3 \\
	     \end{array} \right]$$

In [8]:
A = np.array([[2,1,3],[0,-1,1],[1,0,3]], float)
I = np.identity(len(A))
M = np.concatenate((A,I), axis=1)

print ('Matriz ampliada:')
print (M)

print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (Mgj )

print ('Matriz inversa:')
Ainv = Mgj[:,3:6]
print(Ainv)

Matriz ampliada:
[[ 2.  1.  3.  1.  0.  0.]
 [ 0. -1.  1.  0.  1.  0.]
 [ 1.  0.  3.  0.  0.  1.]]
Matriz após eliminação:
[[ 1.   0.   0.   1.5  1.5 -2. ]
 [ 0.   1.   0.  -0.5 -1.5  1. ]
 [ 0.   0.   1.  -0.5 -0.5  1. ]]
Matriz inversa:
[[ 1.5  1.5 -2. ]
 [-0.5 -1.5  1. ]
 [-0.5 -0.5  1. ]]


### Exercícios

---

> **1.** ([Larson, 2017](https://integrada.minhabiblioteca.com.br/reader/books/9788522127238/pageid/33)) Obtenha, caso exista, a solução para os seguintes sistemas lineares utilizando os métodos eliminação de Gauss-Jordan e Matriz inversa).
>
> a) $\begin{aligned} 2 x+y-z+2 w & =-6 \\ 3 x+4 y+w & =1 \\ x+5 y+2 z+6 w & =-3 \\ 5 x+2 y-z-w= & 3\end{aligned}$
>
> 
> 
> b) $\begin{aligned} x_1+x_2-2 x_3+3 x_4+2 x_5 & =9 \\ 3 x_1+3 x_2-x_3+x_4+x_5 & =5 \\ 2 x_1+2 x_2-x_3+x_4-2 x_5 & =1 \\ 4 x_1+4 x_2+x_3-3 x_5 & =4 \\ 8 x_1+5 x_2-2 x_3-x_4+2 x_5 & =3\end{aligned}$
>
> 
> 
> c) $\begin{array}{rr}x_1-x_2+2 x_3+2 x_4+6 x_5= & 6 \\ 3 x_1-2 x_2+4 x_3+4 x_4+12 x_5= & 14 \\ x_2-x_3-x_4-3 x_5= & -3 \\ 2 x_1-2 x_2+4 x_3+5 x_4+15 x_5= & 10 \\ 2 x_1-2 x_2+4 x_3+4 x_4+13 x_5= & 13\end{array}$
>
> 
> 
> d) $\begin{array}{rr}x_1+2 x_2-2 x_3+2 x_4-x_5+3 x_6= & 0 \\ 2 x_1-x_2+3 x_3+x_4-3 x_5+2 x_6= & 17 \\ x_1+3 x_2-2 x_3+x_4-2 x_5-3 x_6= & -5 \\ 3 x_1-2 x_2+x_3-x_4+3 x_5-2 x_6= & -1 \\ -x_1-2 x_2+x_3+2 x_4-2 x_5+3 x_6= & 10 \\ x_1-3 x_2+x_3+3 x_4-2 x_5+x_6= & 11\end{array}$

---

> **2.** Obtenha a matriz inversa de
>
> $$A = \begin{bmatrix} 4 & -2 & 1 \\ 2 & 3 & -1 \\ -1 & 1 & 2 \end{bmatrix}$$
>
> aplicando a eliminação de Gauss-Jordan à matriz aumentada $[A \mid I]$ (implemente usando a função `gaussJordan`). Verifique o resultado calculando $AA^{-1}$ e confirmando que se obtém a matriz identidade.

---

> **3. (matriz singular)** Aplique o algoritmo de Gauss-Jordan à matriz aumentada $[A \mid I]$ para
>
> $$A = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 1 & 0 & 1 \end{bmatrix}$$
>
> a) O que acontece durante a eliminação quando você tenta normalizar a segunda linha (dividir pelo pivô)?
>
> b) Calcule o determinante de $A$ e relacione com o que você observou no item (a).
>
> c) O sistema $Ax=b$ com $b=(6,12,2)^T$ possui solução única? Ele possui alguma solução? Justifique.

---

> **4. (custo computacional com múltiplos vetores $b$)** Considere o sistema $Ax=b$ para a matriz
>
> $$A = \begin{bmatrix} 4 & 1 & 0 \\ 1 & 4 & 1 \\ 0 & 1 & 4 \end{bmatrix}$$
>
> e os três vetores $b_1=(1,2,3)^T$, $b_2=(0,1,0)^T$ e $b_3=(5,-1,2)^T$.
>
> a) Obtenha as três soluções aplicando a eliminação de Gauss-Jordan separadamente em cada matriz aumentada $[A \mid b_i]$.
>
> b) Calcule a inversa $A^{-1}$ uma única vez e obtenha as três soluções fazendo $x_i = A^{-1}b_i$.
>
> c) Explique por que, quando é necessário resolver o sistema para vários vetores $b$ diferentes com a mesma matriz $A$, calcular $A^{-1}$ uma única vez é mais vantajoso do que repetir a eliminação de Gauss-Jordan para cada $b_i$.

---

> **5. (aplicação: circuito elétrico)** As correntes de malha $i_1$, $i_2$ e $i_3$ (em ampères) de um circuito elétrico satisfazem o sistema
>
> $$\begin{aligned}
> 10 i_1 - 2 i_2 - 3 i_3 &= 5\\
> -2i_1+8i_2-i_3&=0\\
> -3i_1-i_2+9i_3&=3
> \end{aligned}$$
>
> Resolva o sistema (a) pela eliminação de Gauss-Jordan e (b) pela matriz inversa, e confirme que as duas abordagens fornecem o mesmo resultado.

---

> **6.** Considere um dos sistemas $Ax=b$ resolvidos na Seção 3.2 (decomposição LU) ou na Seção 3.4 (métodos iterativos).
>
> a) Resolva-o também pela eliminação de Gauss-Jordan e pela matriz inversa.
>
> b) Se você precisasse resolver esse mesmo sistema repetidamente, apenas alterando o vetor $b$ a cada vez, qual dos métodos estudados até aqui (Gauss-Jordan direto, matriz inversa, decomposição LU ou um método iterativo) você escolheria? Justifique sua resposta com base no número de operações necessárias em cada nova resolução.