# 0.3 Comandos básicos em  Numpy

Numpy é o pacote fundamental para programação científica que proporciona um objeto tipo **array** para armazenar dados de forma eficiente e dispõe de uma série de funções para operar e manipular esses dados. Para usar Numpy, uma vez que já esteja instalado, é importá-lo. Para isso podemos usar a seguinte linha de comando, que importa e chama de **np**.

In [1]:
import numpy as np

## Deferença entre listas e arrays 

Os arrays do Numpy são muito parecidos com as listas do Python, mas possuem diferenças importantes que devem ser conhecidas. Uma diferença importante é que as listas do Python podem armazenar diferentes tipos de dados (int, floar, str, etc) enquanto os arrays do NumPy são homogêneos (mesmo tipo de dado) e representam vetores e matrizes de tamanho fixo, ou seja, não podem ser redimensionados (sem criar um novo array).

Por exemplo, observe que a forma de acessar elementos de _lista_ e de _array_ é a mesma 

In [2]:
x = [1, 2, 3, -1]     # x é uma lista do python  
y = [-2, 3, 0.3, 1]   # y também é uma lista do python
print (x[2])          # imprime o 3º elemento de x
print (y[-1])         # imprime o último elemento de y

3
1


In [3]:
import numpy as np
u = np.array([2, 5, 0.5, 10])    # u é um array do numpy
v = np.array([-1, 0.5, 1.2, 3])  # v também é um array do numpy
print (u[0])                     # imprime o 1º elemento de u
print (v[-2])                    # imprime o penúltimo elemento de v

2.0
1.2


Apesar das semalhanças entre listas e arrays, as operações com arrays do Numpy são feitas elemento a elemento. Então, devemos ter cuidado para não confundir as operações com realizadas com arrays e com listas, pois um mesmo operador pode gerar resultados muito diferentes. Veja os exemplos abaixo.

In [4]:
# x e y são listas python
print(2*x) 

[1, 2, 3, -1, 1, 2, 3, -1]


In [5]:
print(x+y)

[1, 2, 3, -1, -2, 3, 0.3, 1]


In [6]:
print(x**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
print(2*v)
print(v+u)
print(v**2)

[-2.   1.   2.4  6. ]
[ 1.   5.5  1.7 13. ]
[1.   0.25 1.44 9.  ]


## Vetores, matrices e arrays multidimensionais

Vetores, matrizes e _arrays_ de dimensões superiores são ferramentas essenciais na computação numérica. Quando um o cálculo deve ser repetido para um conjunto de valores de entrada, é natural e vantajoso representar o dados como _arrays_ e processar cálculos em termos de operações entre _arrays_.

Processamento computacional numérico formulado dessa forma são ditos vetorizados. A computação vetorizada elimina a necessidade de muitos _loops_ explícitos sobre os elementos da matriz, aplicando operações em blocos de dados da matriz. 

O resultado é um código conciso e mais fácil de entender e gerenciar, além disso, permite realizar operações em bibliotecas de baixo nível (BLAS, LAPACK,etc), mais eficientes. Computações vetorizadas podem, portanto, ser significativamente mais rápidas do que cálculos sequenciais elemento a elemento. 

Isso é particularmente importante em uma linguagem interpretada como Python, onde laços elemento a elemento resultam em uma demanda de desempenho significativa. 

No ambiente de computação científica do Python, estruturas de dados eficientes para trabalhar com matrizes são fornecido pela biblioteca NumPy. O núcleo do NumPy é implementado em C e fornece funções eficientes para manipular e processar matrizes. 

À primeira vista, os arrays NumPy têm alguma semelhança com as listas do Python. Mas uma diferença importante é que, enquanto as listas do Python são recipientes genéricos de objetos, os arrays NumPy são homogêneos e datilografam matrizes de tamanho fixo. Homogênea significa que todos os elementos no
array tem o mesmo tipo de dados. Tamanho fixo significa que um array não pode ser redimensionado (sem criar um novo array).

Por essas e outras razões, as operações e funções que atuam nos arrays NumPy podem ser muito mais eficiente do que operações em listas do Python. Além das estruturas de dados para matrizes, o NumPy também fornece uma grande coleção de operadores e funções básicas que atuam nessas estruturas de dados, bem como submódulos com algoritmos de nível superior, como álgebra linear e transformações rápidas de Fourier.


### Criando e manipulando arrays e matrizes
Uma forma simples de criar um array é a partir de uma lista, mas também existem finções para criar array de zeros, ou vazios, conforme é mostrado nos exemplos a seguir.

In [8]:
a = np.array([2, 3, 5, -1])
print (a)

[ 2  3  5 -1]


In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.eye(4,4,1)  # matriz com uma diagonal deslocada formada de 1s

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [12]:
np.empty(3)

array([1., 1., 1.])

In [13]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(2,5,7)  # pontos igualmente espaçados (ini, fim, n de pontos)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Outras operações muito úteis ao lidar com arrays em computação científica e numérica são o recorte de arrays, inversão de linhas ou colunas, concatenação de matrizes, e outras que são exemplificadas a seguir. 

In [15]:
w = np.array([1, 2, -1, 3, -4, 2, 5])


#### Exemplo
construindo a matriz ampliada (A|b) para processar a eliminação de Gauss

In [16]:
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
print (A)

b = np.array([11,-16,17])
print (b)

b = b.reshape(3,1)
print (b)

Ab = np.hstack((A, b))
print (Ab)

[[ 4 -2  1]
 [-2  4 -2]
 [ 1 -2  4]]
[ 11 -16  17]
[[ 11]
 [-16]
 [ 17]]
[[  4  -2   1  11]
 [ -2   4  -2 -16]
 [  1  -2   4  17]]


### Vetorizando uma função

Ocasionalmente é necessário definir novas funções que operam em matrizes numpy em uma base elemento-por-elemento. Uma boa maneira de implementar essas funções é expressá-la em termos de operadores numpy já existentes e expressões, mas em casos em que isso não é possível, a função np. vectorize pode ser uma ferramenta conveniente. Essa função usa uma função não-vetorial e retorna uma função vetorial. Por exemplo, considere a seguinte implementação da função Step Heaviside, que funciona para entrada escalar:


In [17]:
def heaviside(x):
    return 1 if x>0 else 0

print(heaviside(-1))

0


In [18]:
print(heaviside(1.5))

1


In [19]:
import numpy as np
x = np.linspace(-5,5,11)
print (x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [20]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
heaviside = np.vectorize(heaviside)
heaviside(x) 

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Operações básicas com arrays
As operações com arrays do Numpy são feitas elemento a elemento. 

#### Exemplo

In [22]:
import numpy as np
v = np.array([1, 2, 3, -1])
u = np.array([2, 5, 0.5, 10])
print (2*v)

[ 2  4  6 -2]


In [23]:
print (u+v)

[3.  7.  3.5 9. ]


In [24]:
print (3+v)

[4 5 6 2]


In [25]:
print (u*v)

[  2.   10.    1.5 -10. ]


In [26]:
print (u**2)

[  4.    25.     0.25 100.  ]


Calculando o produto interno (ou produto de matrizes)

In [27]:
print (np.dot(u,v))

3.5


In [28]:
A = np.array([[2,1],[-1,4]])
B = np.array([[5,-1],[8,3]])
print(np.dot(A,B))

[[18  1]
 [27 13]]



Somando os elementos de um array

In [29]:
print(np.sum(v))

5


In [30]:
print(np.max(v))

3


## `np.arange` e outras formas de criar sequências

Além de `np.linspace`, a função `np.arange` cria sequências com **passo fixo** (similar ao `range` do Python, mas retorna um array).

In [31]:
import numpy as np

# np.arange(inicio, fim, passo)  — 'fim' não é incluído
print(np.arange(0, 10, 2))        # inteiros pares de 0 a 8
print(np.arange(0.0, 1.0, 0.25))  # passo decimal

# np.linspace(inicio, fim, n)  — 'fim' É incluído
print(np.linspace(0, 1, 5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75]
[0.   0.25 0.5  0.75 1.  ]


## Tipos de dados (`dtype`)

Todo array NumPy armazena elementos de um único tipo de dado. O tipo padrão depende dos valores fornecidos, mas pode ser especificado com o argumento `dtype`.

In [32]:
a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 3.0])
c = np.array([1, 2, 3], dtype=float)

print(a.dtype)   # int64
print(b.dtype)   # float64
print(c.dtype)   # float64

int64
float64
float64


In [33]:
# Converter o tipo com astype()
d = a.astype(float)
print(d, d.dtype)

[1. 2. 3.] float64


## Estatísticas básicas

O NumPy oferece funções de agregação para calcular estatísticas sobre os elementos de um array.

In [34]:
dados = np.array([4.2, 7.1, 3.5, 9.0, 2.8, 6.4, 5.3])

print('Mínimo:         ', np.min(dados))
print('Máximo:         ', np.max(dados))
print('Soma:           ', np.sum(dados))
print('Média:          ', np.mean(dados))
print('Desvio padrão:  ', np.std(dados))
print('Índice do mín.: ', np.argmin(dados))
print('Índice do máx.: ', np.argmax(dados))

Mínimo:          2.8
Máximo:          9.0
Soma:            38.3
Média:           5.471428571428571
Desvio padrão:   2.0225262037605245
Índice do mín.:  4
Índice do máx.:  3


## Indexação booleana

Podemos selecionar elementos de um array usando uma condição booleana — isso é chamado de **boolean indexing** e é muito usado para filtrar dados.

In [35]:
v = np.array([3, -1, 4, -2, 5, -3, 2])

# Máscara booleana
mascara = v > 0
print('Máscara:', mascara)

# Selecionar apenas os positivos
print('Positivos:', v[mascara])

# Forma abreviada
print('Maiores que 2:', v[v > 2])

Máscara: [ True False  True False  True False  True]
Positivos: [3 4 5 2]
Maiores que 2: [3 4 5]


In [36]:
# Substituir valores negativos por zero
v2 = v.copy()
v2[v2 < 0] = 0
print(v2)

[3 0 4 0 5 0 2]


## Reshape — redimensionamento

`reshape()` reorganiza os elementos de um array em uma nova forma, sem copiar os dados.

In [37]:
v = np.arange(12)  # vetor com 12 elementos
print('Original:', v)

M = v.reshape(3, 4)  # matriz 3x4
print('\nReshape (3x4):')
print(M)

C = v.reshape(2, 2, 3)  # array 3D: 2 blocos de 2x3
print('\nReshape (2x2x3):')
print(C)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshape (2x2x3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [38]:
# flatten() retorna uma cópia 1D de qualquer array
print(M.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Resumo

Neste notebook vimos os principais recursos do NumPy para computação científica:

| Funcionalidade | Exemplos |
|---|---|
| Criar arrays | `np.array()`, `np.zeros()`, `np.ones()`, `np.eye()` |
| Sequências | `np.linspace()`, `np.arange()` |
| Tipos de dado | `.dtype`, `.astype()` |
| Operações vetorizadas | `+`, `-`, `*`, `**`, `/` (elemento a elemento) |
| Produto interno/matricial | `np.dot()`, `@` |
| Estatísticas | `np.sum()`, `np.mean()`, `np.std()`, `np.min()`, `np.max()` |
| Indexação booleana | `v[v > 0]` |
| Redimensionamento | `.reshape()`, `.flatten()` |
| Concatenação | `np.hstack()`, `np.vstack()` |
| Vetorizar função | `np.vectorize()` |

O NumPy é a base do ecossistema científico Python: SciPy, Pandas, Matplotlib e muitos outros dependem dele. No próximo notebook veremos como usar o NumPy especificamente para álgebra linear.